// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5S4s_DBYetlhCRQBH4XEp7XS5jzDq9E',
    appId: '1:133820887919:web:5562bace17019f16efae9a',
    messagingSenderId: '133820887919',
    projectId: 'crud-app-7b297',
    authDomain: 'crud-app-7b297.firebaseapp.com',
    storageBucket: 'crud-app-7b297.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvggB3skyewkQTmQmVWl1P7bGybzESTA',
    appId: '1:133820887919:android:99b495a49ec444c8efae9a',
    messagingSenderId: '133820887919',
    projectId: 'crud-app-7b297',
    storageBucket: 'crud-app-7b297.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqME2Eb6C2LkyV-kSm82XBNj56D1W0yoM',
    appId: '1:133820887919:ios:2cc0e141757277f9efae9a',
    messagingSenderId: '133820887919',
    projectId: 'crud-app-7b297',
    storageBucket: 'crud-app-7b297.firebasestorage.app',
    iosBundleId: 'com.example.crudApp',
  );
}
